### PR TITLE
Add watchOS compatibility

### PR DESCRIPTION
**Pull request by fnazarios**
This PR adds watchOS compatibility

### CODE REVIEW

**Comment by daniel-statsig** [comment]
@fnazarios, thank you for the contribution. This conflicts with some changes that are coming with the next version, but I will look at merging it in as best I can.

**Comment by daniel-statsig** [comment]
@fnazarios. This was merged in with https://github.com/statsig-io/ios-sdk/commit/52af1b67e2f96bfdcb369f1cea2794f723be7956.

It is now available in https://github.com/statsig-io/ios-sdk/releases/tag/1.36.0. 

Let me know if you need anything further.

**Comment by fnazarios** [comment]
@daniel-statsig Thanks Daniel. Looks like you've removed [this commit](https://github.com/statsig-io/ios-sdk/pull/9/commits/0feef219a3d3fc911412061fcbd9051fa2837a0f) from the PR. This fixes a crash on the Apple Watch that isn't reproducible on the watchOS simulator

**Comment by daniel-statsig** [comment]
> @daniel-statsig Thanks Daniel. Looks like you've removed [this commit](https://github.com/statsig-io/ios-sdk/pull/9/commits/0feef219a3d3fc911412061fcbd9051fa2837a0f) from the PR. This fixes a crash on the Apple Watch that isn't reproducible on the watchOS simulator

Is that not here: https://github.com/runna-app/statsig-sdk/blob/main/Sources/Statsig/NetworkService.swift#L233-L234

Am I missing something? It looks like that change is in main

**Pull request closed without merging**
